# Generated by Django 4.2.1 on 2023-06-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0002_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polozka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazov_produktu', models.CharField(max_length=100)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile')),
            ],
        ),
    ]
