# Generated by Django 4.2.1 on 2023-06-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozka',
            name='info_nazov_produktu',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='polozka',
            name='info_produktu',
            field=models.TextField(default=''),
        ),
    ]
