# Generated by Django 4.2.1 on 2023-06-17 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_userprofile_email'),
        ('add_product_main', '0002_polozka_info_nazov_produktu_polozka_info_produktu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=5, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
