# Generated by Django 4.2.1 on 2023-06-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0003_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='transport',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
