# Generated by Django 4.2.1 on 2023-06-18 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_userprofile_email'),
        ('add_product_main', '0005_transport_transport_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ceny', to='add_product_main.polozka')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile')),
            ],
        ),
    ]
