# Generated by Django 4.2.1 on 2023-06-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0006_cena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cena',
            name='amount',
            field=models.DecimalField(decimal_places=5, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cena',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cena',
            name='price',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='cena',
            name='unit',
            field=models.CharField(max_length=20),
        ),
    ]
