# Generated by Django 4.2.1 on 2023-06-18 21:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0007_alter_cena_amount_alter_cena_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cena',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polozka',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
