# Generated by Django 4.2.1 on 2023-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0008_cena_created_at_polozka_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozka',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='polozka/%Y/%m/%d/'),
        ),
    ]
