# Generated by Django 4.2.1 on 2023-06-19 10:36

import add_product_main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0009_polozka_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polozka',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=add_product_main.models.upload_to),
        ),
    ]
