# Generated by Django 4.2.1 on 2023-06-19 11:10

import add_product_main.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0010_alter_polozka_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=add_product_main.models.upload_to)),
                ('polozka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_images', to='add_product_main.polozka')),
            ],
        ),
    ]
