# Generated by Django 4.2.1 on 2023-06-23 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0012_polozkatransport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='transport_name',
            new_name='transport_type',
        ),
    ]
