# Generated by Django 4.2.1 on 2023-06-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0013_rename_transport_name_transport_transport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='transport_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
