# Generated by Django 4.2.1 on 2023-06-24 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0014_transport_transport_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polozkatransport',
            name='polozka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozka_transport', to='add_product_main.polozka'),
        ),
        migrations.AlterField(
            model_name='polozkatransport',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polozka_transport', to='add_product_main.transport'),
        ),
    ]
