# Generated by Django 4.2.3 on 2023-09-25 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0014_userprofile_theme'),
        ('add_product_main', '0018_alter_transportloc_polozka'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability_start_date', models.DateField(blank=True, null=True)),
                ('availability_end_date', models.DateField(blank=True, null=True)),
                ('available_until_out_of_stock', models.BooleanField(default=False)),
                ('stock_count', models.PositiveIntegerField(default=0)),
                ('polozka', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='add_product_main.polozka')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login_app.userprofile')),
            ],
        ),
    ]
