version: '3.8'

services:
  web:
    build: .
    command: gunicorn farmeris.wsgi:application --bind unix:/run/gunicorn.sock
    volumes:
      - .:/app
      - static_volume:/home/lol/Documents/farmeris/static
      - media_volume:/home/lol/Documents/farmeris/media
      - /run/gunicorn:/run/gunicorn
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}

volumes:
  postgres_data:
  static_volume:
  media_volume:
