# Generated by Django 4.2.1 on 2023-07-06 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_product_main', '0016_alter_polozkatransport_polozka_and_more'),
        ('chat_polozka', '0002_chatmessage_recipient_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='polozka',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='add_product_main.polozka'),
        ),
    ]
