
#+AUTHOR: Tím Farmeris
#+title: Manifesto pre Podporu Surového Mlieka na Slovensku

* Úvod
V tejto dobe, keď sa stále viac ľudí obracia k prirodzeným a tradičným potravinám, je dôležité hovoriť o surovom mlieku - jeho výhodách, rizikách a potenciáli, ktorý prináša pre našu spoločnosť.

* Inšpirácia manifesta - Aajonus Vonderplanitz
Inšpirovaní Aajonusom Vonderplanitzom, jeho úspechy v oblasti práv za surové mlieko nás motivujú k dosiahnutiu podobných zmien na Slovensku.

* Naša vízia pre surové mlieko na Slovensku
Veríme v právo každého občana Slovenskej Republiky ku prístupu k prírodným, nespracovaným potravinám, vrátane surového mlieka a jeho produktov. Našou misiou je vzdelávať občanov v oblasti výhod konzumácie surového mlieka a presadzovať legislatívne zmeny, ktoré umožnia predaj surového mlieka a produktov z neho, zabezpečujúc tak práva všetkých spotrebiteľov.

** Prečo surové mlieko?
Surové mlieko má dlhú tradíciu a je cené pre svoje výživné hodnoty a charakteristickú chuť. Naším cieľom je umožniť každému dospelému človeku na Slovensku, aby mal možnosť zvoliť si surové mlieko, ak je správne a bezpečne vyrobené.

** Naše ciele:
   - Legislatívna zmena: Spolupracovať so zákonodarcami na Slovensku na príprave a implementácii zákonov, ktoré umožnia predaj surového mlieka a mliečnych výrobkov pre ľudskú spotrebu s primeraným označením surových produktov.
   - Vzdelávanie verejnosti: Vzdelávať verejnosť o výhodách a rizikách spojených s konzumáciou surového mlieka, posilňujúc ich schopnosť robiť informované rozhodnutia.
   - Podpora miestnych farmárov: Podporovať slovenských farmárov pri prijímaní najlepších postupov pre výrobu kvalitného, bezpečného surového mlieka a surových vyŕobkov z neho.
   - Výskum a spolupráca: Spolupracovať s vedcami v oblasti potravinárstva a odborníkmi na zdravie pri priebežnom výskume výživových výhod a bezpečnosti surového mlieka.

** Zasadzujeme sa za jasné a transparentné označovanie
Všetky produkty zo surového mlieka budú jasne a transparentne označené. Toto označenie bude informovať spotrebiteľov o tom, že produkt je nepasterizovaný. Toto označenie nebude možné použiť pre produkty vyrobené zo surového mlieka, ktoré prešli pasterizáciou počas výrobného procesu.

* Spolupráca a Partnerstvo
Chceme spolupracovať nielen s farmármi a vedeckou komunitou, ale aj s rozhodovacími orgánmi a širokou verejnosťou, aby sme dosiahli pozitívnu zmenu.

* Záver manifesta
Pridajte sa k nám v tejto dôležitej iniciatíve. Spoločne môžeme pracovať na vytvorení bezpečného a informovaného prostredia pre konzumáciu surového mlieka na Slovensku. Váš hlas a podpora majú skutočný význam.
