# Generated by Django 4.2.1 on 2023-07-07 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessageGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_general', models.TextField()),
                ('created_at_general', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient_general', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver_general', to=settings.AUTH_USER_MODEL)),
                ('sender_general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_sender_general', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
