# Generated by Django 4.2.1 on 2023-06-14 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Polozka',
        ),
    ]
