# Generated by Django 4.2.1 on 2023-05-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_product', '0002_productadd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadd',
            name='currency',
            field=models.CharField(default='EUR', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='productadd',
            name='unit',
            field=models.CharField(default='kg', max_length=10, null=True),
        ),
    ]
