# Generated by Django 4.2.1 on 2023-05-25 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('add_product', '0003_alter_productadd_currency_alter_productadd_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadd',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='add_product_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
