# Generated by Django 4.2.3 on 2023-08-20 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_alter_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
