# Generated by Django 4.2.3 on 2023-08-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pagination_preference',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
