# Generated by Django 4.2.3 on 2023-08-30 19:30

from django.db import migrations, models
import login_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0010_remove_userprofile_email_remove_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=login_app.models.upload_to2),
        ),
    ]
