# Generated by Django 4.2.3 on 2023-09-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0011_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state_province',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='state_province'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='street_address'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_postal_code',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='zip_postal_code'),
        ),
    ]
