# Generated by Django 4.2.3 on 2023-09-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0013_alter_userprofile_state_province_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
    ]
