# Generated by Django 4.2.3 on 2023-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0014_userprofile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('sk', 'Slovak'), ('en', 'English'), ('cz', 'Czech')], default='sk', max_length=10, verbose_name='preferred language'),
        ),
    ]
