# Generated by Django 4.2.6 on 2023-12-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0015_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='filter_trusted',
            field=models.BooleanField(default=True, verbose_name='filter trusted'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_trusted',
            field=models.BooleanField(default=False, verbose_name='trusted user'),
        ),
    ]
